# /phoenix/lib/common/Makefile
#
# This file is a part of Phoenix operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

LIB = $(COMMON_LIB_NAME)

include $(PHOENIX_ROOT)/make/make.mak
