# /phoenix/unit_tests/triton/Makefile
#
# This file is a part of Phoenix operating system.
# Copyright (c) 2011-2012, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

SUBDIRS = strings

include $(PHOENIX_ROOT)/make/unit_test.mak
