# /phoenix/unit_tests/common/BitString/Makefile
#
# This file is a part of Phoenix operating system.
# Copyright (c) 2011-2012, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

TEST_NAME = BitString
TEST_DESC = Bit strings

TEST_SRCS = \
	$(PHOENIX_ROOT)/lib/common/CommonLib.cpp \
	$(PHOENIX_ROOT)/lib/common/OTextStream.cpp

TEST_DEFS = KERNEL

include $(PHOENIX_ROOT)/make/unit_test.mak
