# /phoenix/unit_tests/common/Makefile
#
# This file is a part of Phoenix operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

SUBDIRS = BitString BuddyAllocator OTextStream Trees

include $(PHOENIX_ROOT)/make/unit_test.mak
