# /phoenix/unit_tests/common/OTextStream/Makefile
#
# This file is a part of Phoenix operating system.
# Copyright (c) 2011, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

TEST_NAME = OTextStream
TEST_DESC = Output text stream

TEST_SRCS = $(PHOENIX_ROOT)/lib/common/OTextStream.cpp

include $(PHOENIX_ROOT)/make/unit_test.mak
