# /phoenix/unit_tests/common/hash/Makefile
#
# This file is a part of Phoenix operating system.
# Copyright (c) 2011-2012, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

TEST_NAME = hash
TEST_DESC = Hash algorithm

TEST_SRCS = \
	$(PHOENIX_ROOT)/lib/common/hash.cpp

include $(PHOENIX_ROOT)/make/unit_test.mak
